apiVersion: v1
kind: Pod
metadata:
  name: tenerity-sample-app
  labels:
    role: myrole
spec:
  containers:
    - name: web
      image: 694963158089.dkr.ecr.eu-west-1.amazonaws.com/spring-helloworld:v1
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
